### ISSUE TITLE
Cargo NDK arguments changed

### ISSUE THREAD

**Issue by tversteeg** [willir/cargo-ndk-android-gradle#11]
It looks like cargo-ndk introduced a breaking change with it's 2.0 release, changing the `--target` & `--platform` arguments. When I install cargo-ndk with `cargo install cargo-ndk --version 1.0.0` it does work.

Maybe it's an idea to also verify the major version of the installed cargo-ndk?

**Comment by jnicholls** [comment]
Good idea @tversteeg.

**Comment by willir** [comment]
Hi, thanks for reporting the issue, I'll try to soon add 2.0 support and add check for `cargo-ndk` version.
