### ISSUE TITLE
about package target folder

### ISSUE THREAD

**Issue by leiiiooo** [willir/cargo-ndk-android-gradle#5]
in my condition, i need package and copy archive to a lib module. so i modify the plugin, for now, if we apply the plugin in app.gradle it will copy archive to app module, if we apply in a library it will copy archive to library module. #4

**Comment by willir** [comment]
Hi, thanks for the pull request. I have a question, and there is a typo. Could you please take a look?

**Comment by leiiiooo** [comment]
ok, which typo, can you show me? I am in rust now,

**Comment by willir** [comment]
I've submitted a comments to you Pull Request. It seems I forgot to click the submit button before :-)

**Comment by willir** [comment]
Fix in e949d1f
